version: '3'
services:
 docker-app:
    image: marcoseduardoss/spring-boot-docker-app
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - docker-postgres
 docker-postgres:
    image: postgres:10.4
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

# https://emmanuelneri.com.br/2017/09/04/executando-aplicacoes-spring-boot-com-docker/